SELECT to_char(CDR_TIMESTAMP,'dd-mm-yyyy') CDR_DATE
,SUBSTR(INSTANCE_ID,1,2) INSTANCE_ID,DIAMETER_RESULT_CODES,SERVICE_KEY,CALL_TYPE,IS_ROAMING,IS_CHARGING_OVERRULED,ISBFT
,COUNT(CALL_REFERENCE_NUMBER) TOTAL
FROM
(SELECT CDR_TIMESTAMP,CALL_REFERENCE_NUMBER,INSTANCE_ID,DIAMETER_RESULT_CODES,SERVICE_KEY,CALL_TYPE,IS_ROAMING,IS_CHARGING_OVERRULED,ISBFT
FROM SCPCDR.INTERNAL_CDR_{day}
WHERE M_MONTH= '{mon}'
UNION ALL
SELECT CDR_TIMESTAMP,CALL_REFERENCE_NUMBER,INSTANCE_ID,DIAMETER_RESULT_CODES,SERVICE_KEY,CALL_TYPE,IS_ROAMING,IS_CHARGING_OVERRULED,ISBFT
FROM SCPCDR.INTERNAL_CDR_{day}@scpcdr_prod_pk_public
WHERE M_MONTH= '{mon}' 
)
GROUP BY to_char(CDR_TIMESTAMP,'dd-mm-yyyy')
,SUBSTR(INSTANCE_ID,1,2),DIAMETER_RESULT_CODES,SERVICE_KEY,CALL_TYPE,IS_ROAMING,IS_CHARGING_OVERRULED,ISBFT