SELECT CDR_DATE
,SUM(total) AS attempt
FROM
(SELECT to_char(CDR_TIMESTAMP,'HH24:MI') AS cdr_date,DIAMETER_RESULT_CODES AS diameter
,count(CALL_REFERENCE_NUMBER) AS total
FROM SCPCDR.INTERNAL_CDR_{day}
WHERE M_MONTH= '{mon}'
AND to_char(CDR_TIMESTAMP,'HH24:MI') >= '{tm1}'
AND to_char(CDR_TIMESTAMP,'HH24:MI') <'{tm2}'
GROUP BY to_char(CDR_TIMESTAMP,'HH24:MI'),DIAMETER_RESULT_CODES
UNION ALL
SELECT to_char(CDR_TIMESTAMP,'HH24:MI') AS cdr_date,DIAMETER_RESULT_CODES AS diameter
,count(CALL_REFERENCE_NUMBER) AS total
FROM SCPCDR.INTERNAL_CDR_{day}@scpcdr_prod_pk_public
WHERE M_MONTH= '{mon}'
AND to_char(CDR_TIMESTAMP,'HH24:MI') >= '{tm1}'
AND to_char(CDR_TIMESTAMP,'HH24:MI') <'{tm2}'
GROUP BY to_char(CDR_TIMESTAMP,'HH24:MI'),DIAMETER_RESULT_CODES
)
GROUP BY CDR_DATE
ORDER BY CDR_DATE