SELECT to_char(TIMESTAMP,'dd-mm-yyyy') CDR_DATE,to_char(TIMESTAMP,'HH24')CDR_HOUR,BASICCAUSE ,INTERNALCAUSE ,ACCESSFLAG 
,COUNT(TRANSACTIONID ) TOTAL
FROM scmcdr.scm_cc_{mon} 
WHERE m_day='{day}' AND to_char(TIMESTAMP,'HH24:MI') < '{min}'
AND ACCESSFLAG IN ('66','67','68','72','73')
GROUP BY to_char(TIMESTAMP,'dd-mm-yyyy'),to_char(TIMESTAMP,'HH24'),BASICCAUSE ,INTERNALCAUSE ,ACCESSFLAG 
ORDER BY to_char(TIMESTAMP,'HH24')